[package]
name = "critical-section"
version = "0.3.0"
edition = "2018"
description = "Cross-platform critical section"
repository = "https://github.com/embassy-rs/critical-section"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = [
    "embedded",
    "no-std",
    "concurrency",
]

[features]

# Set the token size.
# The crate supplying the critical section implementation can set ONE of them.
# Other crates MUST NOT set any of these.
token-bool = []  # Default
token-u8 = []
token-u16 = []
token-u32 = []
token-u64 = []

[dependencies]
bare-metal = "1.0.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
