name: Clippy check

on:
  push:
    branches: [ staging, trying, main ]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo clippy
