name: Clippy check

on:
  push:
    branches: [ staging, trying, main ]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.63
            components: clippy
            override: true
      - name: Build
        run: cargo clippy
      - name: Build for std
        run: cargo clippy --features std
