name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./ci.sh

      - uses: actions/checkout@v2
      - name: Build for AVR with old toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-01-07
          components : rust-src
          target: avr-specs/avr-atmega328p.json
          profile : minimal
          command : build
          args: -- -Zbuild-std=core
