name: Test

on:
  push:
    branches: [ staging, trying, main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test